// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqQT-Tl4vGOouCPUg7topDC2UcyslA9sU',
    appId: '1:323937929439:web:1e23061ccf92b3259b416a',
    messagingSenderId: '323937929439',
    projectId: 'phil-mobile-2db4a',
    authDomain: 'phil-mobile-2db4a.firebaseapp.com',
    storageBucket: 'phil-mobile-2db4a.firebasestorage.app',
    measurementId: 'G-KL0EZ59SL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbk2oMdsQeGVjYxKjh-03yNkVf_T8u0I',
    appId: '1:323937929439:android:77978a930322c5d69b416a',
    messagingSenderId: '323937929439',
    projectId: 'phil-mobile-2db4a',
    storageBucket: 'phil-mobile-2db4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsxnO5-morX15JW2w8HmkxXWyZNfd72No',
    appId: '1:323937929439:ios:a7f44a0f012f85fe9b416a',
    messagingSenderId: '323937929439',
    projectId: 'phil-mobile-2db4a',
    storageBucket: 'phil-mobile-2db4a.firebasestorage.app',
    iosBundleId: 'com.example.philMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsxnO5-morX15JW2w8HmkxXWyZNfd72No',
    appId: '1:323937929439:ios:a7f44a0f012f85fe9b416a',
    messagingSenderId: '323937929439',
    projectId: 'phil-mobile-2db4a',
    storageBucket: 'phil-mobile-2db4a.firebasestorage.app',
    iosBundleId: 'com.example.philMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqQT-Tl4vGOouCPUg7topDC2UcyslA9sU',
    appId: '1:323937929439:web:33b5bf86b60b774a9b416a',
    messagingSenderId: '323937929439',
    projectId: 'phil-mobile-2db4a',
    authDomain: 'phil-mobile-2db4a.firebaseapp.com',
    storageBucket: 'phil-mobile-2db4a.firebasestorage.app',
    measurementId: 'G-3C47XV3JDG',
  );
}
